"use client";

import Link from "next/link";
import { BookOpen, CalendarDays, Check, ChevronRight, GraduationCap, MapPin, MessageCircle, Phone, Target } from "lucide-react";
import { Benefits, ContactStrip, CoursesGrid, EmptyAssetNote, EnquiryForm, Gallery, Hero, Mentor, PageHero, Reveal, SectionHeading, SplitFeature, SuccessPreview, useLanguage } from "./site";
import { contact, t } from "@/data/site-content";

export function HomePage() { const { lang } = useLanguage(); return <>
      <Hero />
  <section className="section"><div className="site-container"><SectionHeading eyebrow={{ mr:"ध्येयाकडे नियोजनबद्ध वाटचाल", en:"A STRUCTURED PATH FORWARD" }} title={{ mr:"आमचे अभ्यासक्रम", en:"Our courses" }} copy={{ mr:"तुमच्या ध्येयाशी जुळणारे परीक्षाभिमुख मार्गदर्शन निवडा.", en:"Choose exam-focused guidance aligned with your goal." }} /><CoursesGrid /></div></section>
  <section className="section section-soft"><div className="site-container"><SectionHeading eyebrow={{mr:"आमची पद्धत",en:"OUR APPROACH"}} title={{mr:"सरकार करिअर अकॅडमी का निवडावी?",en:"Why choose Sarkar Career Academy?"}} align="center"/><Benefits /></div></section>
  <section className="section"><div className="site-container"><div className="heading-row"><SectionHeading eyebrow={{mr:"यशोगाथा",en:"STUDENT SUCCESS"}} title={{mr:"आमच्या विद्यार्थ्यांचे यश",en:"Our students’ success"}} copy={{mr:"सरकार करिअर अकॅडमीच्या विद्यार्थ्यांनी मिळवलेले यश",en:"Achievements earned by Sarkar Career Academy students"}}/><Link href="/success" className="text-link">{lang === "mr" ? "सर्व यशोगाथा पहा" : "View all success stories"}<ChevronRight /></Link></div><SuccessPreview/><EmptyAssetNote type="students"/></div></section>
  <SplitFeature title={{mr:"महाराष्ट्रातील PSI घडवणारी संस्था",en:"An academy shaping PSI aspirants in Maharashtra"}} copy={{mr:"पोलीस व सैन्य भरती प्रशिक्षणासाठी शिस्तबद्ध तयारी, परीक्षाभिमुख सराव आणि योग्य दिशा.",en:"Disciplined preparation, exam-focused practice and clear direction for police and military recruitment."}}><Link href="/psi-police" className="button button-primary">{lang === "mr" ? "PSI / Police भरतीसाठी मार्गदर्शन मिळवा" : "Get PSI / Police guidance"}</Link></SplitFeature>
  <section className="section"><div className="site-container"><Mentor /></div></section>
  <section className="section section-navy"><div className="site-container enquiry-layout"><div><SectionHeading eyebrow={{mr:"प्रवेश व मार्गदर्शन",en:"ADMISSIONS & GUIDANCE"}} title={{mr:"तुमच्या तयारीविषयी आमच्याशी बोला",en:"Talk to us about your preparation"}} copy={{mr:"तुमची परीक्षा निवडा. पुढील माहितीसाठी अकॅडमीशी थेट संपर्क साधा.",en:"Choose your exam and contact the academy directly for further information."}}/><div className="direct-links"><a href="tel:+918805667100"><Phone/>8805667100</a><a href="https://wa.me/918805667100" target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></div></div><EnquiryForm compact /></div></section>
</>; }

export function AboutPage() { const { lang } = useLanguage(); return <><PageHero eyebrow={{mr:"आमची ओळख",en:"OUR STORY"}} title={{mr:"आमच्याबद्दल",en:"About Career Academy"}} copy={{mr:"नाशिकमधील स्पर्धा परीक्षा मार्गदर्शन संस्था — अभ्यास, तयारी आणि विद्यार्थ्यांच्या यशावर केंद्रित.",en:"A competitive exam guidance institute in Nashik, focused on study, preparation and student success."}}/><section className="section"><div className="site-container editorial-grid"><Reveal><span className="eyebrow">CAREER ACADEMY · NASHIK</span><h2>{lang === "mr" ? "स्पर्धा परीक्षेच्या ध्येयाला स्पष्ट दिशा" : "Clear direction for competitive exam goals"}</h2></Reveal><Reveal><p className="lead">{lang === "mr" ? "सरकार करिअर अकॅडमी ही नाशिकस्थित स्पर्धा परीक्षा मार्गदर्शन संस्था आहे. MPSC, PSI, TET तसेच पोलीस व सैन्य भरती परीक्षांसाठी विद्यार्थ्यांना परीक्षाभिमुख तयारीची दिशा दिली जाते." : "Sarkar Career Academy is a Nashik-based competitive examination guidance institute. It provides exam-oriented preparation for MPSC, PSI, TET, police and military recruitment examinations."}</p><p>{lang === "mr" ? "मार्गदर्शन, नियमित सराव, उपयुक्त नोट्स, अभ्यास नियोजन आणि चाचणी तयारी यांच्या माध्यमातून विद्यार्थ्यांच्या तयारीला केंद्रस्थानी ठेवले जाते." : "Guidance, regular practice, useful notes, study planning and test preparation keep each student’s preparation at the centre."}</p></Reveal></div></section><section className="section section-soft"><div className="site-container"><SectionHeading eyebrow={{mr:"अभ्यासाची चौकट",en:"LEARNING FRAMEWORK"}} title={{mr:"तयारीला आवश्यक आधार",en:"The support preparation needs"}} align="center"/><Benefits /></div></section><section className="section"><div className="site-container"><Mentor /></div></section><ContactStrip/></>; }

export function CoursesPage() { return <><PageHero eyebrow={{mr:"परीक्षा निवडा",en:"CHOOSE YOUR EXAM"}} title={{mr:"अभ्यासक्रम",en:"Courses"}} copy={{mr:"MPSC, PSI, TET आणि पोलीस व सैन्य भरतीसाठी केंद्रित मार्गदर्शन.",en:"Focused guidance for MPSC, PSI, TET, police and military recruitment."}}/><section className="section"><div className="site-container"><CoursesGrid/><div className="info-banner"><Target/><div><h3>अधिक माहितीसाठी संपर्क करा</h3><p>Course duration, fees and batch timings are available directly from the academy.</p></div><Link href="/contact" className="button button-primary">Contact</Link></div></div></section><ContactStrip/></>; }

export function ExamPage({ type }: { type: "mpsc" | "psi" | "tet" }) { const { lang } = useLanguage(); const data = type === "mpsc" ? { eyebrow:{mr:"MPSC मार्गदर्शन",en:"MPSC GUIDANCE"}, title:{mr:"MPSC साठी योग्य दिशा, योग्य मार्गदर्शन",en:"The right direction and guidance for MPSC"}, copy:{mr:"परीक्षाभिमुख तयारी, अभ्यास नियोजन आणि स्पर्धा परीक्षा रणनीती.",en:"Exam-focused preparation, study planning and competitive exam strategy."}, points:[{mr:"परीक्षाभिमुख तयारी",en:"Exam-focused preparation"},{mr:"अभ्यासाचे नियोजन",en:"Study planning"},{mr:"स्पर्धा परीक्षा रणनीती",en:"Competitive exam strategy"},{mr:"मोफत मार्गदर्शन कार्यशाळा",en:"Free guidance workshop"}] } : type === "psi" ? { eyebrow:{mr:"PSI / POLICE",en:"PSI / POLICE"}, title:{mr:"महाराष्ट्रातील PSI घडवणारी संस्था",en:"An academy shaping PSI aspirants in Maharashtra"}, copy:{mr:"PSI, पोलीस व सैन्य भरतीसाठी शिस्तबद्ध, परीक्षाभिमुख तयारी.",en:"Disciplined, exam-focused preparation for PSI, police and military recruitment."}, points:[{mr:"PSI परीक्षेची तयारी",en:"PSI exam preparation"},{mr:"पोलीस भरती मार्गदर्शन",en:"Police recruitment guidance"},{mr:"सैन्य भरती प्रशिक्षण",en:"Military recruitment training"},{mr:"नियमित सराव",en:"Regular practice"}] } : { eyebrow:{mr:"TET तयारी",en:"TET PREPARATION"}, title:{mr:"महाराष्ट्र TET साठी केंद्रित तयारी",en:"Focused preparation for Maharashtra TET"}, copy:{mr:"शिक्षक पात्रता परीक्षेसाठी आवश्यक विषय, सराव आणि मार्गदर्शन.",en:"Subjects, practice and guidance required for the Teacher Eligibility Test."}, points:[{mr:"महाराष्ट्र TET मार्गदर्शन",en:"Maharashtra TET guidance"},{mr:"आवश्यक विषयांची तयारी",en:"Essential subject preparation"},{mr:"सराव परीक्षा",en:"Practice tests"},{mr:"उपयुक्त नोट्स",en:"Useful notes"}] }; return <><PageHero eyebrow={data.eyebrow} title={data.title} copy={data.copy}/>{type === "psi" && <SplitFeature title={data.title} copy={data.copy}/>}<section className="section"><div className="site-container program-layout"><div><SectionHeading eyebrow={{mr:"तयारीची दिशा",en:"PREPARATION FOCUS"}} title={{mr:"परीक्षेसाठी आवश्यक आधार",en:"The right foundation for the exam"}}/><div className="check-list">{data.points.map(point => <div key={point.mr}><Check/>{t(point,lang)}</div>)}</div><p className="note">{lang === "mr" ? "अभ्यासक्रमाचा कालावधी, शुल्क व बॅच वेळेसाठी अकॅडमीशी संपर्क करा." : "Contact the academy for course duration, fees and batch timings."}</p></div><EnquiryForm compact/></div></section>{type === "tet" && <section className="section section-soft"><div className="site-container"><SectionHeading eyebrow={{mr:"विद्यार्थी यश",en:"STUDENT SUCCESS"}} title={{mr:"करिअर अकॅडमीचे TET मधील यशस्वी विद्यार्थी",en:"Career Academy’s successful TET students"}} align="center"/><SuccessPreview dedicated/><EmptyAssetNote type="students"/></div></section>}<ContactStrip/></>; }

export function SuccessPage() { return <><PageHero eyebrow={{mr:"विद्यार्थी प्रथम",en:"STUDENTS FIRST"}} title={{mr:"आमच्या विद्यार्थ्यांचे यश",en:"Our students’ success"}} copy={{mr:"सरकार करिअर अकॅडमीच्या विद्यार्थ्यांनी मिळवलेले यश",en:"Achievements earned by Sarkar Career Academy students"}}/><section className="section"><div className="site-container"><SectionHeading eyebrow={{mr:"TET",en:"TET"}} title={{mr:"करिअर अकॅडमीचे TET मधील यशस्वी विद्यार्थी",en:"Career Academy’s successful TET students"}}/><SuccessPreview dedicated/><EmptyAssetNote type="students"/></div></section><section className="section section-soft"><div className="site-container"><SectionHeading eyebrow={{mr:"PSI / POLICE",en:"PSI / POLICE"}} title={{mr:"ध्येयाकडे वाटचाल करणारे विद्यार्थी",en:"Students progressing towards their goals"}}/><SuccessPreview/><p className="note">No marks, ranks or selection percentages are shown without verified source information.</p></div></section><ContactStrip/></>; }

export function WorkshopsPage() { const { lang } = useLanguage(); return <><PageHero eyebrow={{mr:"मार्गदर्शन व संवाद",en:"GUIDANCE & INTERACTION"}} title={{mr:"मार्गदर्शन कार्यशाळा व कार्यक्रम",en:"Guidance workshops and events"}} copy={{mr:"स्पर्धा परीक्षा तयारीसाठी मार्गदर्शन, संवाद आणि विद्यार्थी गौरवाचे क्षण.",en:"Guidance, interaction and student recognition for competitive exam preparation."}}/><section className="section"><div className="site-container event-grid"><Reveal className="event-card featured"><span className="event-status">{lang === "mr" ? "मागील कार्यक्रम" : "Past event"}</span><CalendarDays/><h2>{lang === "mr" ? "MPSC मोफत मार्गदर्शन कार्यशाळा" : "Free MPSC guidance workshop"}</h2><p>{lang === "mr" ? "प्रमुख मार्गदर्शक : प्रा. रविंद्र सरकार" : "Lead mentor: Prof. Ravindra Sarkar"}</p></Reveal><Reveal className="event-card"><span className="event-status">{lang === "mr" ? "मागील कार्यक्रम" : "Past event"}</span><GraduationCap/><h2>{lang === "mr" ? "यशस्वी PSI विद्यार्थ्यांचा सत्कार समारंभ" : "Felicitation ceremony for successful PSI students"}</h2><p>{lang === "mr" ? "यशस्वी विद्यार्थ्यांच्या प्रयत्नांचा गौरव." : "Recognition of successful students’ efforts."}</p></Reveal></div><div className="event-note">{lang === "mr" ? "संदर्भातील कार्यक्रमांना आगामी कार्यक्रम म्हणून दाखवलेले नाही. नवीन कार्यक्रम माहितीसाठी थेट संपर्क करा." : "Reference events are not presented as upcoming. Contact the academy for current event information."}</div></section><ContactStrip/></>; }

export function BooksPage() { const { lang } = useLanguage(); return <><PageHero eyebrow={{mr:"अभ्यासाचा विश्वासू साथीदार",en:"YOUR STUDY COMPANION"}} title={{mr:"अभ्यास साहित्य व पुस्तके",en:"Study material and books"}} copy={{mr:"स्पर्धा परीक्षेच्या तयारीसाठी करिअर अकॅडमीचे अभ्यास साहित्य.",en:"Career Academy study material for competitive exam preparation."}}/><SplitFeature kind="books" title={{mr:"तयारी अधिक नेमकी करणारे साहित्य",en:"Material that makes preparation more focused"}} copy={{mr:"पुस्तकांची पुष्टी केलेली शीर्षके, मुखपृष्ठे व माहिती उपलब्ध झाल्यावर या संग्रहात समाविष्ट केली जाईल.",en:"Confirmed titles, covers and details will be added to this collection when supplied."}}><a href="tel:+918805667100" className="button button-primary"><Phone/>{lang === "mr" ? "माहितीसाठी संपर्क करा" : "Contact for details"}</a></SplitFeature><section className="section"><div className="site-container"><div className="books-empty"><BookOpen/><h2>{lang === "mr" ? "मूळ पुस्तक संग्रह प्रतीक्षेत" : "Original book catalogue pending"}</h2><EmptyAssetNote type="books"/><p>{lang === "mr" ? "पुस्तके घरपोच मिळण्यासाठी संपर्क करा" : "Contact us for home delivery of books"}</p><a href="tel:+918805667100">8805667100</a></div></div></section><ContactStrip/></>; }

export function GalleryPage() { const { lang } = useLanguage(); return <><PageHero eyebrow={{mr:"अकॅडमीतील क्षण",en:"ACADEMY MOMENTS"}} title={{mr:"गॅलरी",en:"Gallery"}} copy={{mr:"विद्यार्थी यश, कार्यशाळा, अभ्यासक्रम आणि अभ्यास साहित्याची दृश्ये.",en:"A visual collection of student success, workshops, courses and study material."}}/><section className="section"><div className="site-container"><div className="filter-pills">{[lang === "mr"?"सर्व":"All",lang === "mr"?"विद्यार्थी यश":"Student success",lang === "mr"?"कार्यशाळा":"Workshops",lang === "mr"?"अकॅडमी":"Academy",lang === "mr"?"पुस्तके":"Books"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div><Gallery interactive/><p className="note">{lang === "mr" ? "अधिकृत अकॅडमी व कार्यक्रम छायाचित्रे उपलब्ध झाल्यावर गॅलरी विस्तारित केली जाईल." : "The gallery will expand when official academy and event photographs are supplied."}</p></div></section></>; }

export function ContactPage() { const { lang } = useLanguage(); const mapQuery = encodeURIComponent("R K Circle, Pethe Vidyalaya, Nashik 422001"); return <><PageHero eyebrow={{mr:"आमच्याशी बोला",en:"TALK TO US"}} title={{mr:"संपर्क व प्रवेश चौकशी",en:"Contact and admission enquiry"}} copy={{mr:"अभ्यासक्रम, पुस्तके आणि मार्गदर्शनाविषयी माहिती मिळवा.",en:"Get information about courses, books and guidance."}}/><section className="section"><div className="site-container contact-layout"><div><SectionHeading eyebrow={{mr:"मुख्य केंद्र · नाशिक",en:"MAIN CENTRE · NASHIK"}} title={{mr:"भेट द्या किंवा थेट संपर्क करा",en:"Visit or contact us directly"}}/><div className="contact-cards"><div><MapPin/><h3>{lang === "mr"?"नाशिक केंद्र":"Nashik centre"}</h3><p>{t(contact.nashik,lang)}</p><a href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank" rel="noreferrer">{lang === "mr"?"दिशानिर्देश मिळवा":"Get directions"}</a></div><div><Phone/><h3>{lang === "mr"?"फोन":"Phone"}</h3>{contact.phones.map(p=><a key={p} href={`tel:+91${p}`}>{p}</a>)}</div><div><MapPin/><h3>{lang === "mr"?"शाखा":"Branch"}</h3><p>{t(contact.branch,lang)}</p></div></div><div className="map-frame"><iframe title="Career Academy Nashik map" loading="lazy" src={`https://www.google.com/maps?q=${mapQuery}&output=embed`}/></div></div><div className="form-panel"><h2>{lang === "mr"?"मार्गदर्शनासाठी संपर्क करा":"Request guidance"}</h2><p>{lang === "mr"?"तुमची माहिती भरा किंवा थेट Call / WhatsApp करा.":"Share your details or contact us directly by Call / WhatsApp."}</p><EnquiryForm/><div className="direct-links"><a href="tel:+918805667100"><Phone/>Call</a><a href="https://wa.me/918805667100" target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a></div></div></div></section></>; }
